Repository medizininformatik-initiative/mii-process-feasibility, pull requests merged in 2022-10, with the labels that each got.

#31 Adjust Flare Config EnvVars to Match Code
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
Labels: bug

#34 Remove Existing Keystore Before Generation
  feasibility-dsf-process-docker-test-setup/rebuild.sh
Labels: bug

#35 Adjust Dependency Config for DIC 3 BPE Test Setup
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
Labels: bug

#29 Update to DSF Version 0.9.0
  .gitignore
  feasibility-dsf-process-docker-test-setup/dic-1/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/dic-2/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/dic-3/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
  feasibility-dsf-process-docker-test-setup/set-rights.sh
  feasibility-dsf-process-docker-test-setup/zars/bpe/last_event/README.md
  feasibility-dsf-process-tools/pom.xml
  feasibility-dsf-process/README.md
  feasibility-dsf-process/pom.xml
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/message/SendDicRequest.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/AggregateMeasureReports.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/DownloadFeasibilityResources.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/DownloadMeasureReport.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/PrepareForFurtherEvaluation.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/SelectResponseTarget.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/StoreLiveResult.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/StoreMeasureReport.java
Labels: operation

#36 Release v0.4.0
  .gitignore
  feasibility-dsf-process-docker-test-setup/data/feasibility-bundle.json
  feasibility-dsf-process-docker-test-setup/dic-1/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/dic-2/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/dic-3/bpe/last_event/README.md
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
  feasibility-dsf-process-docker-test-setup/rebuild.sh
  feasibility-dsf-process-docker-test-setup/set-rights.sh
  feasibility-dsf-process-docker-test-setup/zars/bpe/last_event/README.md
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/pom.xml
  feasibility-dsf-process-tools/pom.xml
  feasibility-dsf-process/README.md
  feasibility-dsf-process/pom.xml
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/FeasibilityProcessPluginDefinition.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/message/SendDicRequest.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/AggregateMeasureReports.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/DownloadFeasibilityResources.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/DownloadMeasureReport.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/PrepareForFurtherEvaluation.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/SelectResponseTarget.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/StoreLiveResult.java
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/service/StoreMeasureReport.java
  feasibility-dsf-process/src/main/resources/bpe/feasibilityExecute.bpmn
  feasibility-dsf-process/src/main/resources/bpe/feasibilityRequest.bpmn
  pom.xml
Labels: Release

#38 Enhancement/21 add test setup for hapi with cql
  feasibility-dsf-process-docker-test-setup/README.md
  feasibility-dsf-process-docker-test-setup/db/init-db.sh
  feasibility-dsf-process-docker-test-setup/dic-4-store-init/init.sh
  feasibility-dsf-process-docker-test-setup/dic-4-store-init/library-fhir-helpers.json
  feasibility-dsf-process-docker-test-setup/dic-4-store-init/library-fhir-model-definition.json
  feasibility-dsf-process-docker-test-setup/dic-4/bpe/cache/.gitkeep
  feasibility-dsf-process-docker-test-setup/dic-4/bpe/log/README.md
  feasibility-dsf-process-docker-test-setup/dic-4/bpe/plugin/README.md
  feasibility-dsf-process-docker-test-setup/dic-4/bpe/process/README.md
  feasibility-dsf-process-docker-test-setup/dic-4/fhir/conf/README.md
  feasibility-dsf-process-docker-test-setup/dic-4/fhir/log/README.md
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
  feasibility-dsf-process-docker-test-setup/proxy/conf.d/dic-4.conf
  feasibility-dsf-process-docker-test-setup/secrets/db_dic_4_bpe_user.password
  feasibility-dsf-process-docker-test-setup/secrets/db_dic_4_bpe_user_camunda.password
  feasibility-dsf-process-docker-test-setup/secrets/db_fhir_dic_4_user.password
  feasibility-dsf-process-docker-test-setup/secrets/db_fhir_dic_4_user_permanent_delete.password
  feasibility-dsf-process-docker-test-setup/set-rights.sh
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/tools/generator/BundleGenerator.java
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/tools/generator/CertificateGenerator.java
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/tools/generator/EnvGenerator.java
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/src/main/resources/bundle-templates/dic-4-bundle.xml
  feasibility-dsf-process-tools/feasibility-dsf-process-test-data-generator/src/main/resources/bundle-templates/zars-bundle.xml
  feasibility-dsf-process/pom.xml
Labels: documentation, enhancement

#37 Update Workflow Actions to Remove Deprecation Warnings
  .github/workflows/ci.yml
Labels: operation

#40 Fix Communication to Flare
  feasibility-dsf-process-docker-test-setup/data/feasibility-bundle.json
  feasibility-dsf-process-docker-test-setup/dic-1/flare/feasibility-code-tree.json
  feasibility-dsf-process-docker-test-setup/dic-1/flare/feasibility-mapping.json
  feasibility-dsf-process-docker-test-setup/docker-compose.yml
  feasibility-dsf-process/pom.xml
  feasibility-dsf-process/src/main/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientImpl.java
  feasibility-dsf-process/src/test/java/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/FlareWebserviceClientImplIT.java
  feasibility-dsf-process/src/test/resources/de/medizininformatik_initiative/feasibility_dsf_process/client/flare/valid-structured-query.json
Labels: bug
